TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += omibthx.db
DATA += omibthx.proto

#=======================================
include $(TOP)/configure/RULES
